import type { NextPage } from 'next'
import Head from 'next/head'

import CodeEditor from '../components/CodeEditor'
import Editor from '../components/Editor'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.quilljs.com/1.3.6/quill.snow.css"
          rel="stylesheet"
        />
      </Head>
      {/* <nav>
        <Navbar />
      </nav> */}
      <main className="min-h-screen grid gap-2 grid-cols-2">
        <div className="">
          <Editor />
        </div>
        <div className="h-full">
          <CodeEditor />
        </div>
      </main>
    </>
  )
}
export default Home
